### ISSUE TITLE
installing the certificate in the local machine steps are missing

### ISSUE THREAD

**Issue by sumanyaram** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#10]
downloaded the solution and was able to complete the setup.

Do we need to install the certificate in the local machine? How about the private keys?
When we use the makecert command mentioned in the steps, it does not create the private keys.

Are we missing some steps? Please help.

Doubt : When we add the certificate in the azure active directory, will the federation metadata.xml file gets the changes reflected?

Can you please help us with sample JWT token generation.

**Comment by RehanSaeed** [comment]
+1

**Comment by dstrockis** [comment]
The makecert command should install the cert in the local machine.

Please look for an update to the instructions in the next week or so that will leverage private keys.

The certificates uploaded to Azure AD in this sample are not used for signing tokens - they are used for client authentication in the OAuth client credentials grant.  So no, the federation metadata will not be modified.

We're looking into new tooling for things like sample token generation.  For now your best bet is to either run a sample client or pop an authentication request into a browser and perform an interactive sign in.
